---
name: App-Xssh
version: 0.8
author:
  - 'Evan Giles <egiles@cpan.org>'
abstract: Encapsulates the application logic for xssh
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/egiles/app-xssh
requires:
  Config::General: 2.4
  Getopt::Long: 2.37
  Moose: 1.09
  Pod::Usage: 1.35
  UNIVERSAL::require: 0
  X11::Terminal: 0.2
  perl: v5.6.1
configure_requires:
  Module::Build: 0.340201
provides:
  App::Xssh:
    file: lib/App/Xssh.pm
    version: 0.8
  App::Xssh::Config:
    file: lib/App/Xssh/Config.pm
    version: 0.8
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
